### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by geistc01** [smallzhong/cs_cheater#1]
为什么放在vs2019里编译，会出现类型转换不适应的问题，希望作者大大能够解答一下，谢谢。

**Comment by smallzhong** [comment]
需要在编译选项里面把sdl检查去掉

**Comment by smallzhong** [comment]
![image](https://user-images.githubusercontent.com/55563027/145660585-1565c81c-21d6-4174-aa5d-f0f432cad5d9.png)
这个改成否

**Comment by geistc01** [comment]
谢谢你 能加个QQ一起学习交流码
