### ISSUE TITLE
求个release

### ISSUE THREAD

**Issue by Slevin-Wong** [smallzhong/cs_cheater#2]

**Comment by smallzhong** [comment]
很久很久之前写的了，写得太烂了，没法release。。现在好像都跑不起来了
建议在网上找别的代码用，我这个自己都看不下去（

**Comment by smallzhong** [comment]
这个版本好像有bug，跑一段时间会崩溃，之前的某个版本是没bug的，那时候也不知道弄个branch，全在master上面更新，还是建议找别的代码看，网上cs1.6的代码太多了
